# Generated by Django 3.2.7 on 2021-09-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='url',
            field=models.TextField(max_length=200),
        ),
    ]
