# Generated by Django 3.2.7 on 2021-09-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210927_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
