# Generated by Django 3.2.7 on 2021-09-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210927_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='crawl_skip',
            field=models.BooleanField(default=False),
        ),
    ]
