# Generated by Django 3.2.7 on 2021-09-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stock_crawl_skip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystock',
            name='rsi',
            field=models.FloatField(null=True),
        ),
    ]
