# Generated by Django 3.2.7 on 2021-09-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_dailystock_rsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sauce',
            field=models.CharField(default='yahoo', max_length=10),
        ),
    ]
