# Generated by Django 3.2.7 on 2021-09-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stock_sauce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='sauce',
        ),
    ]
