# Generated by Django 3.2.7 on 2021-09-30 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_stock_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='active',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='crawl_skip',
        ),
    ]
