# Generated by Django 3.2.7 on 2021-10-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20210930_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystock',
            name='amount_of_change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailystock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stocks', to='stock.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.market'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.sector'),
        ),
    ]
